//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCore.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightCore.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active registration group with name &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ActiveRegistrationGroupNotFoundFormat {
            get {
                return ResourceManager.GetString("ActiveRegistrationGroupNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad stream content, empty or malformed not found..
        /// </summary>
        internal static string BadStreamContent {
            get {
                return ResourceManager.GetString("BadStreamContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml configuration file not found. Path: &apos;{0}&apos;..
        /// </summary>
        internal static string ConfigurationFileNotFoundFormat {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract type for following registration cannot be empty. Registration: &apos;{0}&apos;..
        /// </summary>
        internal static string ContractTypeCannotBeEmptyFormat {
            get {
                return ResourceManager.GetString("ContractTypeCannotBeEmptyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load type: &apos;{0}&apos;, maybe wrong full qualified info. Try e.g.: &quot;Namespace.Type, Assembly&quot;. Or check bin folder and copy DLLs if necessary..
        /// </summary>
        internal static string CouldNotLoadTypeFormat {
            get {
                return ResourceManager.GetString("CouldNotLoadTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation type for following registration cannot be empty. Registration: &apos;{0}&apos;..
        /// </summary>
        internal static string ImplementationTypeCannotBeEmptyFormat {
            get {
                return ResourceManager.GetString("ImplementationTypeCannotBeEmptyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration section &apos;{0}&apos; not found..
        /// </summary>
        internal static string SectionNotFoundFormat {
            get {
                return ResourceManager.GetString("SectionNotFoundFormat", resourceCulture);
            }
        }
    }
}
